apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-service
  namespace: inkasalud
  labels:
    app: cliente-service
    app.kubernetes.io/part-of: inkasalud-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente-service
  template:
    metadata:
      labels:
        app: cliente-service
    spec:
      containers:
        - name: cliente-service
          image: inkasalud/cliente-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: inkasalud-config
                  key: SPRING_PROFILES_ACTIVE
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: inkasalud-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: inkasalud-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: inkasalud-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inkasalud-secrets
                  key: MYSQL_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
