apiVersion: v1
kind: Service
metadata:
  name: cliente-service
  namespace: inkasalud
  labels:
    app: cliente-service
    app.kubernetes.io/part-of: inkasalud-system
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: cliente-service
