apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: inkasalud
  labels:
    app: frontend
    app.kubernetes.io/part-of: inkasalud-system
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app: frontend
