apiVersion: v1
kind: ConfigMap
metadata:
  name: inkasalud-config
  namespace: inkasalud
  labels:
    app.kubernetes.io/part-of: inkasalud-system
data:
  # MySQL Configuration
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"

  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"

  # Eureka Configuration
  EUREKA_URL: "http://discovery-server:8761/eureka/"

  # JWT Configuration
  JWT_EXPIRATION: "86400000"

  # Spring Profile
  SPRING_PROFILES_ACTIVE: "docker"
