apiVersion: v1
kind: Secret
metadata:
  name: inkasalud-secrets
  namespace: inkasalud
  labels:
    app.kubernetes.io/part-of: inkasalud-system
type: Opaque
stringData:
  # MySQL Credentials
  MYSQL_ROOT_PASSWORD: "admin123"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "admin123"

  # RabbitMQ Credentials
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"

  # JWT Secret
  JWT_SECRET: "inkasaludSecretKeyForJwtTokenSigningWithHS256AlgorithmMustBeLong2024"
