apiVersion: v1
kind: Service
metadata:
  name: catalogo-service
  namespace: inkasalud
  labels:
    app: catalogo-service
    app.kubernetes.io/part-of: inkasalud-system
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: catalogo-service
