apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: inkasalud
  labels:
    app: config-server
    app.kubernetes.io/part-of: inkasalud-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: inkasalud/config-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: inkasalud-config
                  key: SPRING_PROFILES_ACTIVE
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
